Repository GopediaPro/sabangnet_API, pull requests merged in 2025-06, with the labels that each got.

#30 Feat:DB to xlsx
  crud/product_crud.py
  utils/convert_xlsx.py
Labels: feature

#34 Test: python webhook connection and n8n product registration test.
  core/settings.py
  services/product_create.py
  utils/sabangnet_formatter.py
Labels: test

#37 Feat/product db insert api
  api/product_api.py
  crud/product_crud.py
  main.py
  models/product/test_product_raw_data.py
  services/product_xml_parse.py
Labels: feature

#44 feat/n8n fastapi connection
  api/v1/endpoints/products.py
  controller/product.py
  crud/product_crud.py
  main.py
  utils/sabangnet_formatter.py
Labels: feature, fix
